
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATRAS = 10;
  public static final int INSTRUCCION = 2;
  public static final int COMA = 5;
  public static final int APAGAR = 15;
  public static final int BAJA = 7;
  public static final int ENCENDER = 14;
  public static final int NUMEROS = 16;
  public static final int ADELANTE = 9;
  public static final int IZQUIERDA = 11;
  public static final int EOF = 0;
  public static final int ALTA = 6;
  public static final int PARENTESIS_CERRADO = 4;
  public static final int DERECHA = 12;
  public static final int error = 1;
  public static final int PARAR = 13;
  public static final int PARENTESIS_ABIERTO = 3;
  public static final int MEDIA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INSTRUCCION",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "ALTA",
  "BAJA",
  "MEDIA",
  "ADELANTE",
  "ATRAS",
  "IZQUIERDA",
  "DERECHA",
  "PARAR",
  "ENCENDER",
  "APAGAR",
  "NUMEROS"
  };
}

